name: Report

on:
  workflow_dispatch:
    inputs:
      points:
        description: 'Status Data'
        required: true
        type: string
      currdate:
        description: 'Today's Date'
        required: true
        type: string
      currday:
        description: 'Current Day'
        required: true
        type: string

env:
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  DAILY_REPORT_FROM: ${{ secrets.DAILY_REPORT_FROM }}
  DAILY_REPORT_TO: ${{ secrets.DAILY_REPORT_TO }}
  DAILY_REPORT_TO_CC: ${{ secrets.DAILY_REPORT_TO_CC }}
  points: ${{ inputs.points }}
  currdate: ${{ inputs.currdate }}
  currday: ${{ inputs.currday }}

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: node src/main.js